version: "3.5"

services:
    redis:
        container_name: redis
        hostname: redis
        image: "redis:5"
        ports:
            - "6379:6379"
        networks:
            hostnet: {}

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "16379:8081"
        networks:
            hostnet: {}

networks:
    hostnet:
        external: true
        name: network_apps