server:
    port: 8090

spring:
   cache:
      type: redis
      redis:
         key-prefix: poc-cache
         time-to-live: 3600000
   redis:
      host: localhost
      port: 6379

management:
   endpoints:
      jmx:
         exposure:
            exclude: shutdown
            include: '*'
      web:
         exposure:
            exclude: shutdown
            include: '*'
   metrics:
      export:
         prometheus:
            enabled: true
   endpoint:
      shutdown:
         enabled: true
      health:
         show-details: always
      metrics:
         enabled: false
      prometheus:
         enabled: true
   info:
      git:
         mode: full